name: Continuous Integration

# This workflow is triggered on pushes and pull requests to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify your Python version here

    - name: Install Dependencies
      run: make install

    - name: Format Code
      run: make format

    - name: Run Linter
      run: make lint

    - name: Run Tests
      run: make test
